using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Rebound.GlobalTrader.BuildSettingsCode {

	public class Enumerations {

		/// <summary>
		/// Site Language
		/// This is a copy from the GlobalLanguage.List enumeration from the main part of the App
		/// </summary>
		public enum SiteLanguage {
			English = 1,
			German = 2,
			Spanish = 3,
			Italian = 4,
			Thai = 5,
			Afrikaans = 6,
			Belarusian = 7,
			Bulgarian = 8,
			Czech = 10,
			Welsh = 11,
			Danish = 12,
			German_Austria = 13,
			German_Switzerland = 14,
			Greek = 15,
			English_Australia = 16,
			English_Canada = 17,
			English_Ireland = 18,
			English_NewZealand = 19,
			English_UnitedStates = 20,
			English_SouthAfrica = 21,
			English_Zimbabwe = 22,
			Spanish_Argentina = 23,
			Spanish_Bolivia = 24,
			Spanish_Chile = 25,
			Spanish_Colombia = 26,
			Spanish_CostaRica = 27,
			Spanish_DominicanRepublic = 28,
			Spanish_Ecuador = 29,
			Spanish_Guatemala = 30,
			Spanish_Honduras = 31,
			Spanish_Mexico = 32,
			Spanish_Nicaragua = 33,
			Spanish_Panama = 34,
			Spanish_Peru = 35,
			Spanish_PuertoRico = 36,
			Spanish_Paraguay = 37,
			Spanish_ElSalvador = 38,
			Spanish_Uruguay = 39,
			Spanish_Venezuela = 40,
			Estonian = 41,
			Basque = 42,
			Finnish = 43,
			French_Belgium = 44,
			French_Canada = 45,
			French_Switzerland = 46,
			French = 47,
			French_Luxembourg = 48,
			French_Monaco = 49,
			Gujarati = 51,
			Hebrew = 52,
			Hindi = 53,
			Hrvatski_BosnaiHercegovina = 54,
			Croatian = 55,
			Hungarian = 56,
			Armenian = 57,
			Indonesian = 58,
			Icelandic = 59,
			Italian_Switzerland = 60,
			Japanese = 61,
			Georgian = 62,
			Kazakh = 63,
			Kannada = 64,
			Korean = 66,
			Konkani = 67,
			Kyrgyz = 69,
			Lithuanian = 70,
			Latvian = 71,
			Macedonian = 72,
			Mongolian = 73,
			Marathi = 74,
			Malay = 75,
			Maltese = 76,
			Dutch_Belgium = 77,
			Dutch = 78,
			Norwegian = 79,
			Punjabi = 80,
			Polish = 81,
			Portuguese_Brazil = 82,
			Portuguese = 83,
			Romanian = 84,
			Russian = 85,
			Sanskrit = 86,
			Slovak = 87,
			Slovenian = 88,
			Albanian = 89,
			Swedish = 91,
			Kiswahili_Kenya = 92,
			Syriac = 93,
			Tamil = 94,
			Telugu = 95,
			Turkish = 96,
			Tatar = 97,
			Ukrainian = 98,
			Urdu = 99,
			Vietnamese = 101,
			Chinese = 102,
			Chinese_HongKong = 103,
			Chinese_Macau = 104,
			Chinese_Singapore = 105,
			Chinese_Taiwan = 106
		}

	}
}
